### ISSUE TITLE
Should we simplify NQP::Config creation?

### ISSUE THREAD

**Issue by pmurias** [perl6/nqp-configure#2]
I think it would make sense to get rid of the tie and runtime NQP::Config::* subclass loading.
Any reasons why we want to keep that instead of using NQP::Config::Rakudo->new(...)?

**Comment by vrurg** [comment]
No reason whatsoever. It just remains of the initial design which I haven't got time to wipe out completely as there're more important things to do.

**Comment by vrurg** [comment]
Actually, done.
