### ISSUE TITLE
The path functions assume Unix paths will work

### ISSUE THREAD

**Issue by b2gills** [perl6/nqp-configure#3]
In `nfp` it assumes that `splitpath` and `splitdir` will work with Unix paths. This is not guaranteed.
It happens to work only because `File::Spec::Win32` inherits from `File::Spec::Unix`, and they are close enough.
(A small change to `File::Spec::Win32` may break the existing code.)

```perl
sub nfp {
    my ( $vol, $dirs, $file ) = File::Spec->splitpath(shift); # <--
    return File::Spec->catpath( $vol,
        File::Spec->catdir( File::Spec->splitdir($dirs) ), $file ); # <--
}
```

It should really use `File::Spec::Unix->split[path|dir]`.
```perl
sub nfp {
    my ( $vol, $dirs, $file ) = File::Spec::Unix->splitpath(shift);
    #                           ^--------- Unix ----------^
    #      v---- whatever ---v
    return File::Spec->catpath( $vol,
        File::Spec->catdir( File::Spec::Unix->splitdir($dirs) ), $file );
    #   ^--- whatever ---^  ^--------- Unix ---------^
}
```

Think of the above code as `path.decode('Unix').encode($current-system)`.
The existing code would then be `path.decode($current-system).encode($current-system)`, which is not correct.

`File::Spec::Unix` should be used anywhere it is assumed to be a Unix path, and `File::Spec` everywhere else.

With the above changes, it should work on any system we care to support in the future.
(The existing code will not work properly on MacOS Classic, and may not work on VMS.)

---

Also there is no reason to load `File::Spec::Win32` because it will be loaded automatically if it needs to be.

**Comment by vrurg** [comment]
@b2gills The notion of Unix-style paths in the doc is rather a guideline for the users. Anyway, the original idea was to get rid of possible duplication of directory separators. Just Imagine `@prefix@/dir` on Windows if prefix is set with trailing `\`. But `canonpath` resolves this kind of situation and should be ok for the purpose.

Both `::Unix` and `::Win32` are abandoned remains of old experiments. Though `::Unix` will make sense now.

Thanks!

**Comment by b2gills** [comment]
I just noticed that it seemed like there were macros for converting from Unix to native, and it resolved to `nfp`.
(Still looking at the changes in the pull request.)

**Comment by vrurg** [comment]
You noticed right. I was just trying to implement DWIM but only took Win and *nix into consideration.
